apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: default
spec:
  interval: 15m
  path: "./flux/fullCICD/app1/deployment"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app1