apiVersion: v1
kind: Service
metadata:
  labels:
    app: dep-app1
  name: srv-dep-app1
  namespace: default
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: dep-app1
  type: ClusterIP

